### ISSUE TITLE
Will there be drag & drop suppoort?

### ISSUE THREAD

**Issue by non-descriptive** [Yandrik/kolibri#1]
There are two flavors of it: widget rearragnement drag&drop and file drag&drop. 
I mostly interested in the latter. Will you add support for it or kolibri targets strictly embeded?

**Comment by Yandrik** [comment]
File drag&drop is unlikely to be implemented in Kolibri itself, as it's reliant on the runtime. Kolibri runs on desktop using the embedded graphics simulator. This means that file drag&drop needs to be implemented there first, which I don't think it is.
If you want support for this, I'd recommend looking at adding support for it to the embedded-graphics simulator. There aren't any plans to integrate this into Kolibri tho at the moment.

Widget rearrangement drag&drop is very complex in Kolibri, because it focuses on hyper-efficient redrawing. So, all widgets that get covered even partially need to be redrawn. This is really hard using the immediate mode model, because it's near impossible to choose which widgets to redraw, and which to ignore. Therefore, this isn't a planned feature for now.
